name: Build and deploy Node.js app to Azure Web App - IntelligentForms

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install and build
        run: |
          cd 'Intelligent-Forms'
          npm install
          npm run build --if-present

      - name: Create deployment package
        run: |
          cd 'Intelligent-Forms'
          zip -r deployment.zip *

      - name: Upload deployment package to Azure
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp deployment source config-zip \
              --name IntelligentForms \
              --resource-group <your-resource-group> \
              --src deployment.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download publish profile
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'IntelligentForms'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_443ECB5572FC4DEE895B11F3E15AD678 }}
          package: .
